Get Spoiler Position
pedro2555/SimConnectTest pull request #42
Opened 2018-06-19 18:31 UTC by pikachu1992

2018-06-20 21:47 UTC, pedro2555 commented
`git rebase dev`

2018-06-20 21:59 UTC, pikachu1992 commented
Fiz git rebase dev e diz "Current branch Get-Spoiler-Position is up to date."

2018-06-20 23:01 UTC, pedro2555 commented
`git pull origin dev`

E o origin é este repositorio

2018-06-21 00:19 UTC, pedro2555 requested changes
Remove o campo lights, e tenta fazer rebase de novo bum commit unico

2018-06-21 00:20 UTC, pedro2555 requested changes
Remove o campo lights, e tenta fazer rebase de novo bum commit unico

2018-06-21 00:45 UTC, closed without merging